run:
  concurrency: 8
  deadline: 10m
  issues-exit-code: 1
  tests: false

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - experimental
  gci:
    local-prefixes: github.com/alexandear/websocket-pubsub

linters:
  disable-all: true
  enable:
    - lll

issues:
  exclude-rules:
    - linters:
        - lll
      source: "^//go:generate "
